# Generated by Django 5.2.6 on 2025-09-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_kodu', models.CharField(max_length=100)),
                ('renk', models.CharField(max_length=50)),
                ('beden', models.CharField(max_length=20)),
                ('adet', models.PositiveIntegerField()),
                ('aciklama', models.TextField(blank=True)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='order_images/')),
                ('order_no', models.CharField(blank=True, max_length=60, unique=True)),
                ('order_type', models.CharField(choices=[('SERI', 'Seri'), ('OZEL', 'Özel')], default='SERI', max_length=5)),
                ('status', models.CharField(choices=[('NEW', 'Yeni'), ('INPROG', 'Üretimde'), ('DONE', 'Tamamlandı'), ('PARTIAL', 'Kısmi')], default='NEW', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('season', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
