# Generated by Django 5.2.6 on 2025-10-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_dikim_tarihi_order_dikim_yapan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='beden',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
