# Generated by Django 5.2.6 on 2025-10-04 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_beden_order_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='en',
            new_name='renk',
        ),
    ]
