# Generated by Django 5.2.6 on 2025-10-08 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_en_order_renk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='ad',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='beden',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='renk',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='siparis_numarasi',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='siparis_tarihi',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='siparis_tipi',
            field=models.CharField(blank=True, choices=[('ÖZEL', 'Özel'), ('SERI', 'Seri')], db_index=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='teslim_tarihi',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='urun_kodu',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
