# Generated by Django 5.2.6 on 2025-10-09 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_musteri_ad_alter_order_beden_alter_order_renk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='order',
            name='musteri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.musteri'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['siparis_tipi'], name='core_order_siparis_db06db_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['musteri'], name='core_order_musteri_5a7f85_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['urun_kodu'], name='core_order_urun_ko_8d291b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['renk'], name='core_order_renk_f2f816_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['beden'], name='core_order_beden_d142cc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['siparis_tarihi'], name='core_order_siparis_5952be_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['teslim_tarihi'], name='core_order_teslim__a4b6ce_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['siparis_tipi', 'musteri'], name='core_order_siparis_90c72d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['urun_kodu', 'renk', 'beden'], name='core_order_urun_ko_eac172_idx'),
        ),
    ]
