# Generated by Django 5.2.6 on 2025-10-09 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_options_alter_order_musteri_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_siparis_db06db_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_musteri_5a7f85_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_urun_ko_8d291b_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_renk_f2f816_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_beden_d142cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_siparis_5952be_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_teslim__a4b6ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_siparis_90c72d_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_urun_ko_eac172_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='musteri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.musteri'),
        ),
    ]
