# Generated by Django 5.2.6 on 2025-10-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='order',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
