# Generated by Django 5.2.6 on 2025-10-16 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_order_qr_code_order_qr_code_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fasoncu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nakisci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='dikim_durum',
            field=models.CharField(choices=[('bekliyor', 'Bekliyor'), ('basladi', 'Başladı'), ('bitti', 'Bitti')], default='bekliyor', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='dikim_fason',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='dikim_fason_durumu',
            field=models.CharField(blank=True, choices=[('verildi', 'Verildi'), ('alindi', 'Alındı')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='hazir_durum',
            field=models.CharField(choices=[('bekliyor', 'Bekliyor'), ('basladi', 'Başladı'), ('bitti', 'Bitti')], default='bekliyor', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='kesim_durum',
            field=models.CharField(choices=[('bekliyor', 'Bekliyor'), ('basladi', 'Başladı'), ('bitti', 'Bitti')], default='bekliyor', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='nakis_durumu',
            field=models.CharField(choices=[('yok', 'Yok'), ('verildi', 'Nakışa Verildi'), ('alindi', 'Nakıştan Alındı')], default='yok', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='sevkiyat_durum',
            field=models.CharField(choices=[('bekliyor', 'Bekliyor'), ('hazirlaniyor', 'Hazırlanıyor'), ('gonderildi', 'Gönderildi')], default='bekliyor', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='susleme_durum',
            field=models.CharField(choices=[('bekliyor', 'Bekliyor'), ('basladi', 'Başladı'), ('bitti', 'Bitti')], default='bekliyor', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='susleme_fason',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='susleme_fason_durumu',
            field=models.CharField(blank=True, choices=[('verildi', 'Verildi'), ('alindi', 'Alındı')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dikim_fasoncu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dikim_fasonlari', to='core.fasoncu'),
        ),
        migrations.AddField(
            model_name='order',
            name='susleme_fasoncu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susleme_fasonlari', to='core.fasoncu'),
        ),
        migrations.AddField(
            model_name='order',
            name='nakisci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nakis_siparisleri', to='core.nakisci'),
        ),
    ]
