# Generated by Django 5.2.6 on 2025-10-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_orderevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderevent',
            options={'ordering': ['timestamp']},
        ),
    ]
