# Generated by Django 5.2.6 on 2025-10-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_orderevent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderevent',
            options={},
        ),
    ]
