# Generated by Django 5.2.6 on 2025-10-18 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_orderevent_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderevent',
            name='gorev',
            field=models.CharField(choices=[('yok', 'Yok'), ('kesim', 'Kesim'), ('dikim', 'Dikim'), ('susleme', 'Süsleme'), ('hazir', 'Hazır'), ('sevkiyat', 'Sevkiyat'), ('nakis', 'Nakış')], default='yok', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorev', models.CharField(choices=[('yok', 'Yok'), ('kesim', 'Kesim'), ('dikim', 'Dikim'), ('susleme', 'Süsleme'), ('hazir', 'Hazır'), ('sevkiyat', 'Sevkiyat'), ('nakis', 'Nakış')], default='yok', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
