# Generated by Django 5.2.6 on 2025-10-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_orderevent_gorev_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderevent',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='adet',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='ortak_calisanlar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='parca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['order'], name='core_ordere_order_i_35db96_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['user'], name='core_ordere_user_3989a6_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['stage'], name='core_ordere_stage_618a24_idx'),
        ),
    ]
