# Generated by Django 5.2.6 on 2025-10-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_orderevent_aciklama_orderevent_adet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderevent',
            name='fasoncu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_fasonlari', to='core.fasoncu'),
        ),
    ]
