# Generated by Django 5.2.6 on 2025-10-20 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_orderevent_fasoncu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('kesim', 'Kesim'), ('dikim', 'Dikim'), ('susleme', 'Süsleme'), ('sevkiyat', 'Sevkiyat')], max_length=20)),
                ('adet', models.PositiveIntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_counts', to='core.order')),
            ],
        ),
    ]
