# Generated by Django 5.2.6 on 2025-10-20 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_productioncount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderevent',
            name='nakisci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_nakisleri', to='core.nakisci'),
        ),
        migrations.DeleteModel(
            name='ProductionCount',
        ),
    ]
