# Generated by Django 5.2.6 on 2025-10-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_orderevent_nakisci_delete_productioncount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_kodu', models.CharField(max_length=100, unique=True)),
                ('maliyet', models.DecimalField(decimal_places=2, max_digits=12)),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR')], default='TRY', max_length=3)),
            ],
        ),
    ]
