# Generated by Django 5.2.6 on 2025-10-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_productcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ekstra_maliyet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='gitti_mi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='maliyet_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='maliyet_para_birimi',
            field=models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR')], default='TRY', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='maliyet_uygulanan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='para_birimi',
            field=models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR')], default='TRY', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='satis_fiyati',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
