# Generated by Django 5.2.6 on 2025-10-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_order_ekstra_maliyet_order_gitti_mi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='gitti_mi',
        ),
    ]
