# Generated by Django 5.2.6 on 2025-10-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_order_gitti_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='musteri_referans',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Müşteri Sipariş Referansı'),
        ),
    ]
