# Generated by Django 5.2.6 on 2025-10-29 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_order_musteri_referans'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='siparis_resimleri/', verbose_name='Görsel')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.order', verbose_name='Bağlı Sipariş')),
            ],
            options={
                'verbose_name': 'Sipariş Görseli',
                'verbose_name_plural': 'Sipariş Görselleri',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
