# Generated by Django 5.2.6 on 2025-10-30 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_orderimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderimage',
            options={},
        ),
        migrations.AddField(
            model_name='orderimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='temp_uploads/'),
        ),
        migrations.AlterField(
            model_name='orderimage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='core.order'),
        ),
    ]
