# Generated by Django 5.2.6 on 2025-11-09 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_orderimage_options_orderimage_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasoncu',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fasoncu',
            name='notlar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fasoncu',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
