# Generated by Django 5.2.6 on 2025-11-10 20:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_fasoncu_eklenme_tarihi_fasoncu_notlar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nakisci',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nakisci',
            name='notlar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nakisci',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
