# Generated by Django 5.2.6 on 2025-11-11 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_nakisci_eklenme_tarihi_nakisci_notlar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='siparis_tipi',
            field=models.CharField(blank=True, choices=[('ÖZEL', 'Özel'), ('SERI', 'Seri'), ('STOK', 'Stoğa Üretim')], db_index=True, max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='DepoStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_kodu', models.CharField(db_index=True, max_length=100)),
                ('renk', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('beden', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('adet', models.PositiveIntegerField(default=0)),
                ('depo', models.CharField(choices=[('KORIDOR', 'Koridor'), ('SHOWROOM', 'Showroom'), ('SHOWROOM_MUTF', 'Showroom Mutfak'), ('DANTEL_YANI', 'Dantel Odası Yanı'), ('ELISI', 'Elişi Deposu')], default='KORIDOR', max_length=20)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_kaydi', to='core.order')),
            ],
        ),
    ]
