# Generated by Django 5.2.6 on 2025-11-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_order_siparis_tipi_depostok'),
    ]

    operations = [
        migrations.CreateModel(
            name='UretimGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun', models.CharField(max_length=100)),
                ('asama', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
