# Generated by Django 5.2.6 on 2025-11-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_uretimgecmisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cikti_alindi',
            field=models.BooleanField(default=False),
        ),
    ]
