# Generated by Django 5.2.6 on 2025-11-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_order_cikti_alindi'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteri',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
    ]
