# Generated by Django 5.2.6 on 2025-11-13 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_userprofile_gorev_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gorev',
            field=models.CharField(choices=[('yok', 'Yok'), ('kesim', 'Kesim'), ('dikim', 'Dikim'), ('susleme', 'Süsleme'), ('hazir', 'Hazır'), ('sevkiyat', 'Sevkiyat'), ('nakis', 'Nakış')], default='yok', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
