# Generated by Django 5.2.6 on 2025-11-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_order_last_updated_orderseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('stage', 'Aşama Güncellemesi'), ('order_update', 'Sipariş Güncellemesi')], default='stage', max_length=20),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='old_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
