# Generated by Django 5.2.6 on 2025-11-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_orderevent_event_type_orderevent_new_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('stage', 'Aşama Güncellemesi'), ('order_update', 'Sipariş Güncellemesi')], default='stage', max_length=21),
        ),
    ]
