# Generated by Django 5.2.6 on 2025-11-13 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_orderevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='fasoncu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fasoncu'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='nakisci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nakisci'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='stage',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['event_type'], name='core_ordere_event_t_6921b7_idx'),
        ),
    ]
