# Generated by Django 5.2.6 on 2025-11-15 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_notification_url_notification_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='uretimgecmisi',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uretim_gecmisi', to='core.order'),
        ),
    ]
