# Generated by Django 5.2.6 on 2025-11-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_uretimgecmisi_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='siparis_tipi',
            field=models.CharField(blank=True, choices=[('ÖZEL', 'Özel'), ('SERI', 'Seri'), ('STOK', 'Stoğa Üretim')], db_index=True, max_length=20, null=True),
        ),
    ]
