# Generated by Django 5.2.6 on 2025-11-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_beden_renk_urunkod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beden',
            name='ad',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='renk',
            name='ad',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='urunkod',
            name='kod',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
