# Generated by Django 5.2.6 on 2025-12-10 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_beden_ad_alter_renk_ad_alter_urunkod_kod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timeout_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='siparis_tipi',
            field=models.CharField(blank=True, choices=[('OZEL', 'Özel'), ('SERI', 'Seri'), ('STOK', 'Stoğa Üretim')], db_index=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MesaiKayit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giris_zamani', models.DateTimeField(blank=True, null=True)),
                ('cikis_zamani', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
