# Generated by Django 5.2.6 on 2025-12-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_userprofile_timeout_free_alter_order_siparis_tipi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('stage', 'Aşama Güncellemesi'), ('order_update', 'Sipariş Güncellemesi'), ('system', 'Sistem')], default='stage', max_length=20),
        ),
    ]
